apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-b12705014
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-b12705014
  template:
    metadata:
      labels:
        app: nginx-b12705014
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-b12705014
spec:
  selector:
    app: nginx-b12705014
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 80
    nodePort: 30001
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-b12705014
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-b12705014
  template:
    metadata:
      labels:
        app: mysql-b12705014
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-b12705014-password
              key: password

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-b12705014
spec:
  selector:
    app: mysql-b12705014
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-b12705014
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin-b12705014
  template:
    metadata:
      labels:
        app: phpmyadmin-b12705014
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        ports:
        - containerPort: 80
        env:
        - name: PMA_HOST
          value: "mysql-b12705014"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-b12705014-password
              key: password

---

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-b12705014
spec:
  selector:
    app: phpmyadmin-b12705014
  ports:
  - protocol: TCP
    port: 8887
    targetPort: 80
  type: NodePort

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-b12705014-password
type: Opaque
data:
  password: Ym93ZW5jaGVuQXQxNg==